<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="collection_import_contract.bat" />
    <None Remove="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ACTCore.CollectionService.Application\ACTCore.CollectionService.Application.csproj" />
    <ProjectReference Include="..\ACTCore.CollectionService.Domain\ACTCore.CollectionService.Domain.csproj" />
    <ProjectReference Include="..\ACTCore.CollectionService.Infrastructure\ACTCore.CollectionService.Infrastructure.csproj" />
    <ProjectReference Include="..\ACTCore.CollectionService.Utilities\ACTCore.CollectionService.Utilities.csproj" />
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="collection_import_contract.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="collection_import_employee.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>
    <ItemGroup>
	    <None Update="appsettings.json">
		    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    </None>
    </ItemGroup>

</Project>
